name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
       
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore github4women/github4women.csproj
        
      - name: Build
        run: dotnet build github4women/github4women.csproj --no-restore --configuration Release
      
      - name: Test
        run: dotnet test github4women/github4women.csproj --no-build --verbosity normal