name: Teste schedule
# Executa de hora em hora
on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:
    
jobs:
  log_datetime:
    runs-on: ubuntu-latest
    
    steps:
      - name: Exibir data e hora
         run:|
          echo "Teste - Data e Hora Atual:"
          echo "$(date)"
